### ISSUE TITLE
Various issues with the android widget

### ISSUE THREAD

**Issue by kobus-v-schoor** [ente/ente#6235]
### Description

The android widget has a few issues after the new widget types were introduced (memories, albums, etc.).

Issues I've encountered:

1. The images are not rotated correctly (probably not respecting the exif data?)
2. The widget displays a low-res version of the images (probably the thumbnail instead of the original?). Some images that I've previously viewed are high-res
3. The widget sometimes displays videos which it can't play, it probably should just show images?

Also a small suggestion, when displaying album widget and only one album is selected for display, you probably don't need to display the album name (e.g. I only display my favourites).

### Version

v1.1.0

### Last working version

<v1 (original favourites widget worked nicely)

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by szechp** [comment]
I have the same issue with the rotated pictures. Pictures that are captured upright (Portrait Mode) get flipped by 90 degrees when displayed in the widget. They are fine when viewed in the app.

**Comment by prateekmedia** [comment]
We've been testing 1024x1024 image for widget instead of current 512x512 around, I hope that should fix it. Also the rotation would get fixed with that. We don't think removing video thumbnail from widget makes sense so we won't be fixing it.

**Comment by szechp** [comment]
Should this 1024x1024 fix already been rolled out? I still have the same issue

**Comment by szechp** [comment]
another update to the app, still the same issue with images beeing displayed in the wrong orientation.

**Comment by szechp** [comment]
Another issue I found: The Fotos only take a very small pool where it Pulls the random images from. It feels like it's displaying the same 7 images.

**Comment by AmanRajSinghMourya** [comment]
The incorrectly rotated widget images have been fixed in #12514, which is now merged. The separate issue where album widgets repeatedly cycled through the same small cached set was addressed earlier in #10861 and released in Photos v1.3.56. Album widgets now cache up to 50 photos and periodically rebuild that cache to introduce more photos from the selected albums. If this is still happening on v1.3.56 or newer, please contact support at support@ente.com
